### ISSUE TITLE
Existing libraries / ?: universalmutator

### ISSUE THREAD

**Issue by stanislaw** [theofidry/mutation-testing#16]
I am not sure where to put these guys, they are so language-agnostic 😄

https://github.com/agroce/universalmutator

**Comment by mbj** [comment]
language agnostic libs typically do primitive string based source code alterations.

This is bad for 2 reasons:

* Performance, as you have to start running the modified source, bad for startup speed and re-use
* Noise level, as string based substitution easily produces syntax errors that just add "garbage mutations".

I'd not consider such a lib close to production ready.

**Comment by theofidry** [comment]
Well, given that 80% of those libs are abandoned I wouldn't worry much about it being production ready tbh :P Maybe we could add a `experimental` flag if you are worried people will take it seriously but given the lack of popularity I don't think it's much of a concern.

@stanislaw I would be fine with a "language agnostic" section :)

**Comment by mbj** [comment]
@theofidry naming this one as "language agnostic" validates the concept, and as there is no production ready one in that concept (nor I think you can make a stable one) I'd consider that section misleading.

I'd name the section "other".

**Comment by theofidry** [comment]
Closed via #17
