### ISSUE TITLE
Some way to visually differentiate between major and minor tools?

### ISSUE THREAD

**Issue by stanislaw** [theofidry/mutation-testing#6]
Hello,

Not all of the tools in this list are actively maintained. Would be nice to have a visual clue about a tool: whether it is active and whether it actually implements a working mutation testing functionality.

Example: In Java section, only Pitest is a real tool, the other two seem to be abandoned.

I don't have a good proposal for the visual / text solution yet.

Thanks.

**Comment by stanislaw** [comment]
Related question: At this point, the only two real and mature solutions for mutation testing I see in this list are Java/Pitest and Ruby/Mutant. Is there any other solution that can be considered as mature as these two?

We are pushing our Mull (C/C++) towards being production ready but we are not there yet: Mull is still experimental.

Would be nice to differentiate between mature and experimental solutions in this list.

**Comment by stanislaw** [comment]
Actually the two solutions I see:

1) Just create a second section called something like "Existing libraries (Production Ready)" and move these two (or more) tools there. Rename "Existing libraries" to "Existing libraries (Experimental)"

2) Create some sort of badges like "production ready", "experimental", "active"... No clear idea how to design this...

I think solution #1 is the easiest. I can send a PR for this if there is any interest in my proposal.

**Comment by mbj** [comment]
@stanislaw Another great test it:

* Is the tool used on CI right now. CI is "production" for mutation testing tools IMO.

**Comment by theofidry** [comment]
Tbh I started this list more as to keep track of the existing tools regardless of their states. Even a non-maintained library can be interesting to check out.

That said I do see the usage of going a bit further and add more information regarding the state of each of those. My main concern about just updating it manually is that it can easily get out of sync unless you have a kind of health check script in place or regularly go through them

**Comment by mbj** [comment]
@theofidry My idea was that you simply scan for tools usage patterns on opensource projects CI builds. A build that runs the tool in the last N weeks could be an indication the tool is active.

**Comment by theofidry** [comment]
that requires to know which kind of CI is used though: Circle, Travis, AppVeyor or other... Maybe GitHub Insights could be enough? Like checking if there is any activity over the last month?

That said maybe the simplest way to go is to update manually and check it from time to time... it's not like we need real-time accuracy

**Comment by stanislaw** [comment]
> Tbh I started this list more as to keep track of the existing tools regardless of their states. Even a non-maintained library can be interesting to check out.

I was of the same opinion before but recently I realized that there is a difference between some prototype of mutation testing tool and a tool that actually made it into something more serious.

I looked a bit more at the tools from the list and I see that PHP/infection also looks very solid (missed PHP section entirely during my first scan because I am coming from quite distant language communities like C/C++/Swift/Objective-C). 

It is indeed not clear how to differentiate between these two groups of major and minor tools. For me probably the following combination is working:

- date of the last update, activity on the contribution graph
- amount of stars on the project
- presence of CI (@mbj, not sure if it is sufficient criteria but it is definitely quite strong!)

I would start with moving the tools that are clearly major to one section and then see if any other tools from the "Minor" aka experimental/research list will make it too with time.

**Comment by theofidry** [comment]
what about just adding a `[abandoned]` or `[prototype]` tag in front of the lib and put the maintained ones at the top for each language? That way the first one you see are the maintained ones and we still mention the others

**Comment by stanislaw** [comment]
> That said maybe the simplest way to go is to update manually and check it from time to time... it's not like we need real-time accuracy

I agree that manual updates are enough.

> what about just adding a [abandoned] or [prototype] tag in front of the lib and put the maintained ones at the top for each language? That way the first one you see are the maintained ones and we still mention the others

This would work for me. The only (probably minor) concern is readability of the list after many of the items will appear to have these tags.

**Comment by stanislaw** [comment]
Let me try it. I will open a test PR.

**Comment by theofidry** [comment]
Closed via #7
